using MongoDB.Bson.Serialization.Attributes;

namespace PMC_APP.DTOs;

[BsonIgnoreExtraElements]
public class ArticleLabelDTO : ArticleDTO
{
    /// <summary>
    /// Indicates whether the article contains full text.
    /// </summary>
    public bool HasFullText { get; set; }

    /// <summary>
    /// Source type of the article data.
    /// 1 = FTP bulk XML
    /// 2 = Web scraping
    /// </summary>
    public int SourceType { get; set; }

    /// <summary>
    /// Indicates whether the article contains an abstract.
    /// </summary>
    public bool? HasAbstract { get; set; }

    /// <summary>
    /// Username or identifier of the user who scraped the article data.
    /// </summary>
    public string? ScrapedByUser { get; set; }

    /// <summary>
    /// Indicates whether the article has been filtered.
    /// </summary>
    public bool IsFiltered { get; set; } = false;

    /// <summary>
    /// Indicates whether the article is related to a human study.
    /// </summary>
    public bool? IsHumanStudy { get; set; }

    /// <summary>
    /// Keywords that caused the article to be excluded or filtered.
    /// </summary>
    public List<string>? ExcludedKeywords { get; set; }

    /// <summary>
    /// Categories that caused the article to be excluded or filtered.
    /// </summary>
    public List<string>? ExcludedCategories { get; set; }

    /// <summary>
    /// Indicates whether the article has been reviewed
    /// for ingredient labeling.
    /// </summary>
    public bool IsIngredientReviewed { get; set; } = false;

    /// <summary>
    /// Indicates whether the article contains ingredient information.
    /// </summary>
    public bool? ContainsIngredient { get; set; }

    /// <summary>
    /// List of detected ingredients in the article.
    /// </summary>
    public List<string>? Ingredients { get; set; }

    /// <summary>
    /// Indicates whether the article was labeled using an LLM.
    /// </summary>
    public bool IsLlmLabeled { get; set; } = false;

    /// <summary>
    /// Label identifier generated by the LLM.
    /// </summary>
    public int? LlmLabelId { get; set; }

    /// <summary>
    /// Reasoning provided by the LLM for the assigned label.
    /// </summary>
    public string? LlmReasoning { get; set; }
}